### ISSUE TITLE
InventoryClickEvent to ReaperSanction v1.1.0

### ISSUE THREAD

**Issue by Cameleon00722** [Farmeurimmo/Spigot_SanctionSet#2]
sorry it's me again, this error still appears anytime someone open a gui 

[19:44:07 INFO]: Pratal_mox issued server command: /map
[19:44:13 ERROR]: Could not pass event InventoryClickEvent to ReaperSanction v1.1.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1620]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:2002) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1620]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1620]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.NullPointerException
	at main.java.fr.farmeurimmo.reapersanction.gui.GuiManager.onInventoryClick(GuiManager.java:43) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor39.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1620]
	... 15 more

**Comment by Farmeurimmo** [comment]
let me check my code again

**Comment by Farmeurimmo** [comment]
Cloud you try with this jar of the plugin ? https://github.com/Reaper-Solutions/Minecraft-ReaperSanction/releases/download/fix/SanctionSet-1.1.1-SNAPSHOT.jar

**Comment by Cameleon00722** [comment]
sorry for not responding i forgot to send the message

here the log when i interract with a gui 

https://bin.sx/KHWnulICUp

**Comment by Farmeurimmo** [comment]
Did you try with the jar I gave you?

**Comment by Cameleon00722** [comment]
yes

**Comment by Farmeurimmo** [comment]
OK, I think I have a solution. I will give you another jar this evening

**Comment by Farmeurimmo** [comment]
Here is the link (I updated the jar). Should be fixed.

https://github.com/Reaper-Solutions/Minecraft-ReaperSanction/releases/download/fix/SanctionSet-1.1.1-SNAPSHOT.jar
